In [24]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()

c.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = c.fetchall()
table_names=[]

for tables in tables:
    table_names.append(tables[0])

print("Consulta de tablas=" , table_names)


c.execute("SELECT Url, Stars, Forks FROM Repo")

print("-------------")


df_select1 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks'])


display(df_select1)

Consulta de tablas= ['MethodParameter', 'sqlite_sequence', 'Method', 'Solution', 'Repo']
-------------

                                                  Url  Stars  Forks
0        https://github.com/jcnossen/upspring.net.git      2      1
1   https://github.com/castleproject-deprecated/Ca...     97     46
2              https://github.com/Shamar/Epic.NET.git     10     11
3    https://github.com/AnthonyNystrom/GenXSource.git      3      4
4         https://github.com/realsaraf/eConcierge.git      1      0
..                                                ...    ...    ...
88             https://github.com/jdm7dv/research.git      0      0
89  https://github.com/parvbhullar/rdlc.report.eng...      0      0
90          https://github.com/re-motion/TypePipe.git      0      0
91                 https://github.com/tmbx/kwm-ng.git      0      0
92           https://github.com/zqqijian/GitKB288.git      0      0

[93 rows x 3 columns]

# Consulta 1

In [3]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()


c.execute("SELECT Url, Stars, Forks FROM Repo")

print("-------------")


df_select1 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks'])


display(df_select1)

-------------

                                                  Url  Stars  Forks
0        https://github.com/jcnossen/upspring.net.git      2      1
1   https://github.com/castleproject-deprecated/Ca...     97     46
2              https://github.com/Shamar/Epic.NET.git     10     11
3    https://github.com/AnthonyNystrom/GenXSource.git      3      4
4         https://github.com/realsaraf/eConcierge.git      1      0
..                                                ...    ...    ...
88             https://github.com/jdm7dv/research.git      0      0
89  https://github.com/parvbhullar/rdlc.report.eng...      0      0
90          https://github.com/re-motion/TypePipe.git      0      0
91                 https://github.com/tmbx/kwm-ng.git      0      0
92           https://github.com/zqqijian/GitKB288.git      0      0

[93 rows x 3 columns]

# Consulta 2

In [4]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()

c.execute("SELECT Url, Stars, Forks FROM Repo WHERE Stars > 50")

print("-------------")


df_select2 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks'])


display(df_select2)

-------------

                                                 Url  Stars  Forks
0  https://github.com/castleproject-deprecated/Ca...     97     46
1        https://github.com/accord-net/framework.git   2115   1095
2          https://github.com/WildGums/Orchestra.git    112     41
3      https://github.com/Azure/azure-powershell.git    809    814
4   https://github.com/akiver/CSGO-Demos-Manager.git    220     49
5          https://github.com/kunzmi/managedCuda.git    104     30

# Consulta 3

In [6]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()

c.execute("SELECT Url, Stars, Forks FROM Repo WHERE Stars > 50 AND Forks > 100")

print("-------------")


df_select3 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks'])


display(df_select3)

-------------

                                             Url  Stars  Forks
0    https://github.com/accord-net/framework.git   2115   1095
1  https://github.com/Azure/azure-powershell.git    809    814

# Consulta 4

In [9]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()

c.execute("SELECT Url, Stars, Forks, ProcessedTime FROM Repo WHERE Stars > 50 AND Forks > 100")

print("-------------")


df_select4 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks', 'Processed Time'])


display(df_select4)

-------------

,Url,Stars,Forks,Processed Time
0,https://github.com/accord-net/framework.git,2115,1095,636439604479775390
1,https://github.com/Azure/azure-powershell.git,809,814,636474706985884120

# Consulta 5

In [20]:
import sqlite3
import pandas as pd

db_name = "c_sharp_db_15.sqlite"

conn = sqlite3.connect(db_name)
c = conn.cursor()

c.execute("SELECT r.Url, r.Stars, r.Forks, r.ProcessedTime || '  ' || s.ProcessedTime FROM Repo r JOIN Solution s ON r.Id = s.RepoId WHERE r.Stars > 50 AND r.Forks > 100")

print("-------------")


df_select5 = pd.DataFrame(c.fetchall(),columns=['Url', 'Stars', 'Forks', 'Processed Time'])


display(df_select5)

-------------

,Url,Stars,Forks,Processed Time
0,https://github.com/accord-net/framework.git,2115,1095,636439604479775390 636439606201962890
1,https://github.com/Azure/azure-powershell.git,809,814,636474706985884120 636474711379634120